Fix AttributeError in ClusterSeed.mutation_sequence when show_sequence is set to True
AttributeError issue with mutation_sequence function in cluster_seed.py

sage: B = Matrix([[0,1],[-1, 0]])
sage: S = ClusterSeed(B)
sage: S.mutation_sequence([0,1], show_sequence=True)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 1
----> 1 S.mutation_sequence([Integer(0),Integer(1)], show_sequence=True)

File /var/tmp/sage-10.9-current/local/lib/python3.14/site-packages/sage/combinat/cluster_algebra_quiver/cluster_seed.py:2753, in ClusterSeed.mutation_sequence(self, sequence, show_sequence, fig_size, return_output)
   2750     seed_sequence.append(seed)
   2752 if show_sequence:
-> 2753     self.quiver().mutation_sequence2(sequence=sequence, show_sequence=True, fig_size=fig_size)
   2755 if return_output == 'seed':
   2756     return seed_sequence

AttributeError: 'ClusterQuiver' object has no attribute 'mutation_sequence2'

Expeted Behavior

if show_sequence: 'Should call .quiver().mutation_sequence' but calls .quiver.mutation_sequence2 instead!


After Fix:

sage: B = Matrix([[0,1],[-1, 0]])
sage: S = ClusterSeed(B)
sage: S.mutation_sequence([0,1], show_sequence=True)
Launched png viewer for Graphics object consisting of 24 graphics primitives
[A seed for a cluster algebra of rank 2,
 A seed for a cluster algebra of rank 2]